### PR TITLE
Add support for oauth client credential

### PR DESCRIPTION
**Pull request by rh-taro**
add support `grant_type=client_credentials`

OAuth 2.0 Client Credentials
https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_client_credentials_flow.htm&type=5

### CODE REVIEW

**Comment by christi-stripe** [comment]
Is there anything holding this up from merge?

**Comment by timrogers** [comment]
@christi-stripe Hi there! 👋🏻 No - frankly, I just hadn't spotted this PR.

Have you been able to test it to see if it works? Whilst I maintain this gem, I don't have an active Salesforce organisation, so I can't easily test.

**Comment by christi-stripe** [comment]
I have not been able to test because I'm stuck on an old version for the moment, but it looks to me like it should work. I am able to use the Restforce client successfully with oauth client credential flow as follows:

```rb
      response = post(
        base_url,
        path: "/services/oauth2/token",
        query: {
          "grant_type" => "client_credentials",
          "client_id" => client_id,
          "client_secret" => client_secret
        }
      )
      body = JSON.parse(response.body)

      # removed validation for brevity

      client = Restforce.new(
        oauth_token: body["access_token"],
        instance_url: body["instance_url"],
        api_version: "59.0"
      )

      my_case = client.find("Case", "500XXXXXXXXXXXXXXX")
```

**Review by timrogers — APPROVED** [review]
Thanks for submitting this PR, and apologies that I didn't review it for so long 😅 

I'm not able to test this because I don't have my own Salesforce instance these days, but the changes make sense to me and to @christi-stripe, so I'm going to merge this and release it. We can always make tweaks later if it turns out that there are issues!

**Pull request merged**
